# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PunchTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_type', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=64)),
                ('punch_time', models.DateTimeField()),
                ('flags', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecard.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('staff_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='punchtime',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecard.Task'),
        ),
        migrations.AddField(
            model_name='punchtime',
            name='volunteeer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timecard.Volunteer'),
        ),
    ]
