# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punchtime',
            old_name='volunteeer_id',
            new_name='volunteer_id',
        ),
        migrations.AlterField(
            model_name='punchtime',
            name='punch_type',
            field=models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=8),
        ),
    ]
