# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_auto_20161015_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastKnownStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('task_name', models.CharField(max_length=64)),
                ('punch_time_latest', models.DateTimeField()),
                ('punch_type_latest', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=8)),
            ],
            options={
                'db_table': 'timecard_view_last_known_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('branch_name', models.CharField(max_length=64)),
                ('task_name', models.CharField(max_length=64)),
                ('punch_time_in', models.DateTimeField()),
                ('punch_time_out', models.DateTimeField()),
                ('session_time', models.IntegerField()),
                ('flags', models.IntegerField()),
            ],
            options={
                'db_table': 'timecard_view_report',
                'managed': False,
            },
        ),
    ]
