# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0002_auto_20161015_2220'),
        ('timecard', '0004_create_views'),
    ]

    operations = [
    ]
