# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0004_create_views'),
        ('timecard', '0005_create_view_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastKnownStatus',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True)),
                ('staff_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('punch_time_latest', models.DateTimeField()),
                ('punch_type_latest', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=8)),
            ],
            options={
                'db_table': 'view_last_known_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True)),
                ('staff_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('branch_name', models.CharField(max_length=64)),
                ('task_name', models.CharField(max_length=64)),
                ('punch_time_in', models.DateTimeField()),
                ('punch_time_out', models.DateTimeField()),
                ('session_time_hours', models.FloatField()),
            ],
            options={
                'db_table': 'view_report',
                'managed': False,
            },
        ),
    ]
