# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0006_merge_20161015_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchtime',
            name='punch_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
