# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0007_auto_20161016_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
