# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0008_auto_20161016_1810'),
        ('timecard', '0008_volunteer_active'),
    ]

    operations = [
    ]
