# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0011_auto_20170225_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchtime',
            name='adminCheckoutTime',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
