# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0012_auto_20170225_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchtime',
            name='punch_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
